const { spacing, borderRadius, borderWidth, zIndex } = require('./generate-values');

const BREAKPOINTS = {
  '2xl': { min: '1920px', max: '1919px' },
  xl: { min: '1536px', max: '1535px' },
  lg: { min: '1280px', max: '1279px' },
  md: { min: '1024px', max: '1023px' },
  sm: { min: '768px', max: '767px' },
  xs: { min: '360px', max: '360px' },
};

// Default Tailwind config can be checked out here — https://unpkg.com/browse/tailwindcss@3.0.18/stubs/defaultConfig.stub.js
module.exports = {
  theme: {
    screens: {
      '2xl': { max: BREAKPOINTS['2xl'].max },
      xl: { max: BREAKPOINTS.xl.max },
      lg: { max: BREAKPOINTS.lg.max },
      md: { max: BREAKPOINTS.md.max },
      sm: { max: BREAKPOINTS.sm.max },
      xs: { max: BREAKPOINTS.xs.max },

      'xl-up': { min: BREAKPOINTS.xl.min },
      'lg-up': { min: BREAKPOINTS.lg.min },
      'md-up': { min: BREAKPOINTS.md.min },
      'sm-up': { min: BREAKPOINTS.sm.min },
      'xs-up': { min: BREAKPOINTS.xs.min },

      '2xl-only': { min: BREAKPOINTS.xl.min, max: BREAKPOINTS['2xl'].max },
      'xl-only': { min: BREAKPOINTS.lg.min, max: BREAKPOINTS.xl.max },
      'lg-only': { min: BREAKPOINTS.md.min, max: BREAKPOINTS.lg.max },
      'md-only': { min: BREAKPOINTS.sm.min, max: BREAKPOINTS.md.max },
      'sm-only': { min: BREAKPOINTS.xs.min, max: BREAKPOINTS.sm.max },
    },
    colors: ({ colors }) => ({
      inherit: colors.inherit,
      current: colors.current,
      transparent: colors.transparent,
    }),
    spacing: {
      0: '0px',
      px: '1px',
      ...spacing,
    },
    borderRadius: {
      none: '0px',
      full: '9999px',
      ...borderRadius,
    },
    borderWidth: {
      DEFAULT: '1px',
      0: '0px',
      1: '1px',
      3: '3px',
      ...borderWidth,
    },
    minWidth: {
      0: '0px',
      full: '100%',
      min: 'min-content',
      max: 'max-content',
      fit: 'fit-content',
      ...spacing,
    },
    maxWidth: {
      none: 'none',
      0: '0px',
      full: '100%',
      min: 'min-content',
      max: 'max-content',
      fit: 'fit-content',
      prose: '65ch',
      ...spacing,
    },
    minHeight: {
      0: '0px',
      full: '100%',
      screen: '100vh',
      min: 'min-content',
      max: 'max-content',
      fit: 'fit-content',
      ...spacing,
    },
    maxHeight: {
      full: '100%',
      screen: '100vh',
      min: 'min-content',
      max: 'max-content',
      fit: 'fit-content',
      ...spacing,
    },
    letterSpacing: {
      '-5%': '-0.05em',
      '-4%': '-0.04em',
      '-3%': '-0.03em',
      '-2%': '-0.02em',
      '-1%': '-0.01em',
      none: '0em',
      '1%': '0.01em',
      '2%': '0.02em',
      '3%': '0.03em',
      '4%': '0.04em',
      '5%': '0.05em',
    },
    lineHeight: {
      none: 1,
      1.1: 1.1,
      1.2: 1.2,
      1.3: 1.3,
      1.4: 1.4,
      1.5: 1.5,
      1.6: 1.6,
      1.7: 1.7,
      1.8: 1.8,
      1.9: 1.9,
      2: 2,
    },
    zIndex: {
      '-1': -1,
      auto: 'auto',
      0: 0,
      ...zIndex,
    },
  },
  plugins: [require('tailwindcss-safe-area')],
};
